package com.rajamohan.mindmingle.domain.model

/**
 * The seed for `appConfig/plans` — the Firestore doc that MindMingle+ pricing is actually read
 * from. Prices are NOT set from a Cloud Function: any signed-in client reads the doc directly
 * and an admin edits it from the Plan Pricing screen (see firestore.rules, appConfig).
 *
 * Every country in `files/CountryCodes.json` has a row here so the admin screen can list all of
 * them, but only the markets we have actually priced carry non-zero amounts. A zero row means
 * "not priced yet" — checkout falls back to [PlanCatalog.defaultCountry] until an admin fills it
 * in. Dial codes are not duplicated here; they come from [CountryCodeRepository].
 *
 * Amounts are in the currency's smallest unit, which is what Razorpay charges in:
 *   decimals 2 -> paise/cents  (INR 99.00 = 9900)
 *   decimals 0 -> whole units  (JPY 399 = 399)
 *   decimals 3 -> fils         (KWD 0.999 = 999)
 */
data class CurrencySpec(
    val currency: String,
    val symbol: String,
    val decimals: Int,
    val monthly: Long,
    val annual: Long
)

/** Market that is charged when a user's country has no priced row of its own. */
const val DEFAULT_PLAN_COUNTRY: String = "US"

internal val COUNTRY_CURRENCIES: Map<String, CurrencySpec> = mapOf(
    "AD" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "AE" to CurrencySpec("AED", "AED", 2, 1199L, 11999L),
    "AF" to CurrencySpec("AFN", "؋", 2, 0L, 0L),
    "AG" to CurrencySpec("XCD", "EC\$", 2, 0L, 0L),
    "AI" to CurrencySpec("XCD", "EC\$", 2, 0L, 0L),
    "AL" to CurrencySpec("ALL", "L", 2, 0L, 0L),
    "AM" to CurrencySpec("AMD", "֏", 2, 0L, 0L),
    "AN" to CurrencySpec("ANG", "ƒ", 2, 0L, 0L),
    "AO" to CurrencySpec("AOA", "Kz", 2, 0L, 0L),
    "AQ" to CurrencySpec("USD", "\$", 2, 0L, 0L),
    "AR" to CurrencySpec("ARS", "AR\$", 2, 290000L, 2900000L),
    "AS" to CurrencySpec("USD", "\$", 2, 0L, 0L),
    "AT" to CurrencySpec("EUR", "€", 2, 299L, 2999L),
    "AU" to CurrencySpec("AUD", "A\$", 2, 449L, 4499L),
    "AW" to CurrencySpec("AWG", "ƒ", 2, 0L, 0L),
    "AX" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "AZ" to CurrencySpec("AZN", "₼", 2, 0L, 0L),
    "BA" to CurrencySpec("BAM", "KM", 2, 0L, 0L),
    "BB" to CurrencySpec("BBD", "Bds\$", 2, 0L, 0L),
    "BD" to CurrencySpec("BDT", "৳", 2, 29900L, 299900L),
    "BE" to CurrencySpec("EUR", "€", 2, 299L, 2999L),
    "BF" to CurrencySpec("XOF", "CFA", 0, 0L, 0L),
    "BG" to CurrencySpec("BGN", "лв", 2, 0L, 0L),
    "BH" to CurrencySpec("BHD", "BHD", 3, 1199L, 11990L),
    "BI" to CurrencySpec("BIF", "FBu", 0, 0L, 0L),
    "BJ" to CurrencySpec("XOF", "CFA", 0, 0L, 0L),
    "BL" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "BM" to CurrencySpec("BMD", "BD\$", 2, 0L, 0L),
    "BN" to CurrencySpec("BND", "B\$", 2, 0L, 0L),
    "BO" to CurrencySpec("BOB", "Bs", 2, 0L, 0L),
    "BR" to CurrencySpec("BRL", "R\$", 2, 1490L, 14900L),
    "BS" to CurrencySpec("BSD", "B\$", 2, 0L, 0L),
    "BT" to CurrencySpec("BTN", "Nu.", 2, 0L, 0L),
    "BW" to CurrencySpec("BWP", "P", 2, 0L, 0L),
    "BY" to CurrencySpec("BYN", "Br", 2, 0L, 0L),
    "BZ" to CurrencySpec("BZD", "BZ\$", 2, 0L, 0L),
    "CA" to CurrencySpec("CAD", "CA\$", 2, 399L, 3999L),
    "CC" to CurrencySpec("AUD", "A\$", 2, 0L, 0L),
    "CD" to CurrencySpec("CDF", "FC", 2, 0L, 0L),
    "CF" to CurrencySpec("XAF", "FCFA", 0, 0L, 0L),
    "CG" to CurrencySpec("XAF", "FCFA", 0, 0L, 0L),
    "CH" to CurrencySpec("CHF", "CHF", 2, 299L, 2999L),
    "CI" to CurrencySpec("XOF", "CFA", 0, 0L, 0L),
    "CK" to CurrencySpec("NZD", "NZ\$", 2, 0L, 0L),
    "CL" to CurrencySpec("CLP", "CLP\$", 0, 2900L, 29000L),
    "CM" to CurrencySpec("XAF", "FCFA", 0, 0L, 0L),
    "CN" to CurrencySpec("CNY", "CN¥", 2, 1990L, 19900L),
    "CO" to CurrencySpec("COP", "COL\$", 2, 1190000L, 11900000L),
    "CR" to CurrencySpec("CRC", "₡", 2, 0L, 0L),
    "CU" to CurrencySpec("CUP", "\$MN", 2, 0L, 0L),
    "CV" to CurrencySpec("CVE", "\$", 2, 0L, 0L),
    "CX" to CurrencySpec("AUD", "A\$", 2, 0L, 0L),
    "CY" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "CZ" to CurrencySpec("CZK", "Kč", 2, 6900L, 69000L),
    "DE" to CurrencySpec("EUR", "€", 2, 299L, 2999L),
    "DJ" to CurrencySpec("DJF", "Fdj", 0, 0L, 0L),
    "DK" to CurrencySpec("DKK", "kr", 2, 2499L, 24999L),
    "DM" to CurrencySpec("XCD", "EC\$", 2, 0L, 0L),
    "DO" to CurrencySpec("DOP", "RD\$", 2, 0L, 0L),
    "DZ" to CurrencySpec("DZD", "دج", 2, 0L, 0L),
    "EC" to CurrencySpec("USD", "\$", 2, 0L, 0L),
    "EE" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "EG" to CurrencySpec("EGP", "E£", 2, 9900L, 99900L),
    "ER" to CurrencySpec("ERN", "Nfk", 2, 0L, 0L),
    "ES" to CurrencySpec("EUR", "€", 2, 299L, 2999L),
    "ET" to CurrencySpec("ETB", "Br", 2, 0L, 0L),
    "FI" to CurrencySpec("EUR", "€", 2, 299L, 2999L),
    "FJ" to CurrencySpec("FJD", "FJ\$", 2, 0L, 0L),
    "FK" to CurrencySpec("FKP", "£", 2, 0L, 0L),
    "FM" to CurrencySpec("USD", "\$", 2, 0L, 0L),
    "FO" to CurrencySpec("DKK", "kr", 2, 0L, 0L),
    "FR" to CurrencySpec("EUR", "€", 2, 299L, 2999L),
    "GA" to CurrencySpec("XAF", "FCFA", 0, 0L, 0L),
    "GB" to CurrencySpec("GBP", "£", 2, 249L, 2499L),
    "GD" to CurrencySpec("XCD", "EC\$", 2, 0L, 0L),
    "GE" to CurrencySpec("GEL", "₾", 2, 0L, 0L),
    "GF" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "GG" to CurrencySpec("GBP", "£", 2, 0L, 0L),
    "GH" to CurrencySpec("GHS", "GH₵", 2, 3900L, 39900L),
    "GI" to CurrencySpec("GIP", "£", 2, 0L, 0L),
    "GL" to CurrencySpec("DKK", "kr", 2, 0L, 0L),
    "GM" to CurrencySpec("GMD", "D", 2, 0L, 0L),
    "GN" to CurrencySpec("GNF", "FG", 0, 0L, 0L),
    "GP" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "GQ" to CurrencySpec("XAF", "FCFA", 0, 0L, 0L),
    "GR" to CurrencySpec("EUR", "€", 2, 299L, 2999L),
    "GS" to CurrencySpec("GBP", "£", 2, 0L, 0L),
    "GT" to CurrencySpec("GTQ", "Q", 2, 0L, 0L),
    "GU" to CurrencySpec("USD", "\$", 2, 0L, 0L),
    "GW" to CurrencySpec("XOF", "CFA", 0, 0L, 0L),
    "GY" to CurrencySpec("GYD", "G\$", 2, 0L, 0L),
    "HK" to CurrencySpec("HKD", "HK\$", 2, 2500L, 24900L),
    "HN" to CurrencySpec("HNL", "L", 2, 0L, 0L),
    "HR" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "HT" to CurrencySpec("HTG", "G", 2, 0L, 0L),
    "HU" to CurrencySpec("HUF", "Ft", 2, 99900L, 999000L),
    "ID" to CurrencySpec("IDR", "Rp", 2, 3900000L, 39000000L),
    "IE" to CurrencySpec("EUR", "€", 2, 299L, 2999L),
    "IL" to CurrencySpec("ILS", "₪", 2, 1190L, 11900L),
    "IM" to CurrencySpec("GBP", "£", 2, 0L, 0L),
    "IN" to CurrencySpec("INR", "₹", 2, 9900L, 99900L),
    "IO" to CurrencySpec("USD", "\$", 2, 0L, 0L),
    "IQ" to CurrencySpec("IQD", "ع.د", 3, 0L, 0L),
    "IR" to CurrencySpec("IRR", "﷼", 2, 0L, 0L),
    "IS" to CurrencySpec("ISK", "kr", 0, 0L, 0L),
    "IT" to CurrencySpec("EUR", "€", 2, 299L, 2999L),
    "JE" to CurrencySpec("GBP", "£", 2, 0L, 0L),
    "JM" to CurrencySpec("JMD", "J\$", 2, 0L, 0L),
    "JO" to CurrencySpec("JOD", "JD", 3, 0L, 0L),
    "JP" to CurrencySpec("JPY", "¥", 0, 399L, 3990L),
    "KE" to CurrencySpec("KES", "KSh", 2, 39900L, 399900L),
    "KG" to CurrencySpec("KGS", "с", 2, 0L, 0L),
    "KH" to CurrencySpec("KHR", "៛", 2, 0L, 0L),
    "KI" to CurrencySpec("AUD", "A\$", 2, 0L, 0L),
    "KM" to CurrencySpec("KMF", "CF", 0, 0L, 0L),
    "KN" to CurrencySpec("XCD", "EC\$", 2, 0L, 0L),
    "KP" to CurrencySpec("KPW", "₩", 2, 0L, 0L),
    "KR" to CurrencySpec("KRW", "₩", 0, 3900L, 39000L),
    "KW" to CurrencySpec("KWD", "KWD", 3, 999L, 9990L),
    "KY" to CurrencySpec("KYD", "CI\$", 2, 0L, 0L),
    "KZ" to CurrencySpec("KZT", "₸", 2, 0L, 0L),
    "LA" to CurrencySpec("LAK", "₭", 2, 0L, 0L),
    "LB" to CurrencySpec("LBP", "ل.ل", 2, 0L, 0L),
    "LC" to CurrencySpec("XCD", "EC\$", 2, 0L, 0L),
    "LI" to CurrencySpec("CHF", "CHF", 2, 0L, 0L),
    "LK" to CurrencySpec("LKR", "Rs", 2, 89900L, 899000L),
    "LR" to CurrencySpec("LRD", "L\$", 2, 0L, 0L),
    "LS" to CurrencySpec("LSL", "L", 2, 0L, 0L),
    "LT" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "LU" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "LV" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "LY" to CurrencySpec("LYD", "LD", 3, 0L, 0L),
    "MA" to CurrencySpec("MAD", "DH", 2, 0L, 0L),
    "MC" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "MD" to CurrencySpec("MDL", "L", 2, 0L, 0L),
    "ME" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "MF" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "MG" to CurrencySpec("MGA", "Ar", 2, 0L, 0L),
    "MH" to CurrencySpec("USD", "\$", 2, 0L, 0L),
    "MK" to CurrencySpec("MKD", "ден", 2, 0L, 0L),
    "ML" to CurrencySpec("XOF", "CFA", 0, 0L, 0L),
    "MM" to CurrencySpec("MMK", "K", 2, 0L, 0L),
    "MN" to CurrencySpec("MNT", "₮", 2, 0L, 0L),
    "MO" to CurrencySpec("MOP", "MOP\$", 2, 0L, 0L),
    "MP" to CurrencySpec("USD", "\$", 2, 0L, 0L),
    "MQ" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "MR" to CurrencySpec("MRU", "UM", 2, 0L, 0L),
    "MS" to CurrencySpec("XCD", "EC\$", 2, 0L, 0L),
    "MT" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "MU" to CurrencySpec("MUR", "Rs", 2, 13900L, 139000L),
    "MV" to CurrencySpec("MVR", "Rf", 2, 0L, 0L),
    "MW" to CurrencySpec("MWK", "MK", 2, 0L, 0L),
    "MX" to CurrencySpec("MXN", "MX\$", 2, 5900L, 59000L),
    "MY" to CurrencySpec("MYR", "RM", 2, 1299L, 12999L),
    "MZ" to CurrencySpec("MZN", "MT", 2, 0L, 0L),
    "NA" to CurrencySpec("NAD", "N\$", 2, 0L, 0L),
    "NC" to CurrencySpec("XPF", "₣", 0, 0L, 0L),
    "NE" to CurrencySpec("XOF", "CFA", 0, 0L, 0L),
    "NF" to CurrencySpec("AUD", "A\$", 2, 0L, 0L),
    "NG" to CurrencySpec("NGN", "₦", 2, 250000L, 2499900L),
    "NI" to CurrencySpec("NIO", "C\$", 2, 0L, 0L),
    "NL" to CurrencySpec("EUR", "€", 2, 299L, 2999L),
    "NO" to CurrencySpec("NOK", "kr", 2, 3499L, 34999L),
    "NP" to CurrencySpec("NPR", "Rs", 2, 39900L, 399900L),
    "NR" to CurrencySpec("AUD", "A\$", 2, 0L, 0L),
    "NU" to CurrencySpec("NZD", "NZ\$", 2, 0L, 0L),
    "NZ" to CurrencySpec("NZD", "NZ\$", 2, 499L, 4999L),
    "OM" to CurrencySpec("OMR", "OMR", 3, 1199L, 11990L),
    "PA" to CurrencySpec("PAB", "B/.", 2, 0L, 0L),
    "PE" to CurrencySpec("PEN", "S/", 2, 1190L, 11900L),
    "PF" to CurrencySpec("XPF", "₣", 0, 0L, 0L),
    "PG" to CurrencySpec("PGK", "K", 2, 0L, 0L),
    "PH" to CurrencySpec("PHP", "₱", 2, 14900L, 149000L),
    "PK" to CurrencySpec("PKR", "Rs", 2, 79900L, 799900L),
    "PL" to CurrencySpec("PLN", "zł", 2, 1299L, 12999L),
    "PM" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "PN" to CurrencySpec("NZD", "NZ\$", 2, 0L, 0L),
    "PR" to CurrencySpec("USD", "\$", 2, 0L, 0L),
    "PS" to CurrencySpec("ILS", "₪", 2, 0L, 0L),
    "PT" to CurrencySpec("EUR", "€", 2, 299L, 2999L),
    "PW" to CurrencySpec("USD", "\$", 2, 0L, 0L),
    "PY" to CurrencySpec("PYG", "₲", 0, 0L, 0L),
    "QA" to CurrencySpec("QAR", "QAR", 2, 1099L, 10999L),
    "RE" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "RO" to CurrencySpec("RON", "lei", 2, 1399L, 13999L),
    "RS" to CurrencySpec("RSD", "дин", 2, 0L, 0L),
    "RU" to CurrencySpec("RUB", "₽", 2, 0L, 0L),
    "RW" to CurrencySpec("RWF", "FRw", 0, 0L, 0L),
    "SA" to CurrencySpec("SAR", "SAR", 2, 1199L, 11999L),
    "SB" to CurrencySpec("SBD", "SI\$", 2, 0L, 0L),
    "SC" to CurrencySpec("SCR", "₨", 2, 0L, 0L),
    "SD" to CurrencySpec("SDG", "ج.س", 2, 0L, 0L),
    "SE" to CurrencySpec("SEK", "kr", 2, 3499L, 34999L),
    "SG" to CurrencySpec("SGD", "S\$", 2, 399L, 3999L),
    "SH" to CurrencySpec("SHP", "£", 2, 0L, 0L),
    "SI" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "SJ" to CurrencySpec("NOK", "kr", 2, 0L, 0L),
    "SK" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "SL" to CurrencySpec("SLE", "Le", 2, 0L, 0L),
    "SM" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "SN" to CurrencySpec("XOF", "CFA", 0, 0L, 0L),
    "SO" to CurrencySpec("SOS", "Sh", 2, 0L, 0L),
    "SR" to CurrencySpec("SRD", "\$", 2, 0L, 0L),
    "SS" to CurrencySpec("SSP", "£", 2, 0L, 0L),
    "ST" to CurrencySpec("STN", "Db", 2, 0L, 0L),
    "SV" to CurrencySpec("USD", "\$", 2, 0L, 0L),
    "SY" to CurrencySpec("SYP", "£S", 2, 0L, 0L),
    "SZ" to CurrencySpec("SZL", "L", 2, 0L, 0L),
    "TC" to CurrencySpec("USD", "\$", 2, 0L, 0L),
    "TD" to CurrencySpec("XAF", "FCFA", 0, 0L, 0L),
    "TG" to CurrencySpec("XOF", "CFA", 0, 0L, 0L),
    "TH" to CurrencySpec("THB", "฿", 2, 9900L, 99900L),
    "TJ" to CurrencySpec("TJS", "SM", 2, 0L, 0L),
    "TK" to CurrencySpec("NZD", "NZ\$", 2, 0L, 0L),
    "TL" to CurrencySpec("USD", "\$", 2, 0L, 0L),
    "TM" to CurrencySpec("TMT", "m", 2, 0L, 0L),
    "TN" to CurrencySpec("TND", "DT", 3, 0L, 0L),
    "TO" to CurrencySpec("TOP", "T\$", 2, 0L, 0L),
    "TR" to CurrencySpec("TRY", "₺", 2, 9900L, 99900L),
    "TT" to CurrencySpec("TTD", "TT\$", 2, 0L, 0L),
    "TV" to CurrencySpec("AUD", "A\$", 2, 0L, 0L),
    "TW" to CurrencySpec("TWD", "NT\$", 2, 9900L, 99000L),
    "TZ" to CurrencySpec("TZS", "TSh", 2, 0L, 0L),
    "UA" to CurrencySpec("UAH", "₴", 2, 0L, 0L),
    "UG" to CurrencySpec("UGX", "USh", 0, 0L, 0L),
    "US" to CurrencySpec("USD", "\$", 2, 299L, 2999L),
    "UY" to CurrencySpec("UYU", "\$U", 2, 0L, 0L),
    "UZ" to CurrencySpec("UZS", "soʼm", 2, 0L, 0L),
    "VA" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "VC" to CurrencySpec("XCD", "EC\$", 2, 0L, 0L),
    "VE" to CurrencySpec("VES", "Bs.", 2, 0L, 0L),
    "VG" to CurrencySpec("USD", "\$", 2, 0L, 0L),
    "VI" to CurrencySpec("USD", "\$", 2, 0L, 0L),
    "VN" to CurrencySpec("VND", "₫", 0, 69000L, 690000L),
    "VU" to CurrencySpec("VUV", "VT", 0, 0L, 0L),
    "WF" to CurrencySpec("XPF", "₣", 0, 0L, 0L),
    "WS" to CurrencySpec("WST", "WS\$", 2, 0L, 0L),
    "YE" to CurrencySpec("YER", "﷼", 2, 0L, 0L),
    "YT" to CurrencySpec("EUR", "€", 2, 0L, 0L),
    "ZA" to CurrencySpec("ZAR", "R", 2, 4900L, 49900L),
    "ZM" to CurrencySpec("ZMW", "ZK", 2, 0L, 0L),
    "ZW" to CurrencySpec("ZWG", "Z\$", 2, 0L, 0L),
)

/**
 * The catalog to fall back on when `appConfig/plans` is missing or empty, and the one an admin
 * restores with "Restore defaults". [dialCodes] maps ISO country code to dial code and comes from
 * [CountryCodeRepository]; a country with no dial code still gets a row, it just cannot be
 * resolved from a phone number.
 */
fun defaultPlanCatalog(dialCodes: Map<String, String> = emptyMap()): PlanCatalog = PlanCatalog(
    enabled = true,
    defaultCountry = DEFAULT_PLAN_COUNTRY,
    countries = COUNTRY_CURRENCIES.mapValues { (code, spec) ->
        CountryPricing(
            countryCode = code,
            currency = spec.currency,
            symbol = spec.symbol,
            decimals = spec.decimals,
            dialCode = dialCodes[code].orEmpty(),
            monthly = spec.monthly,
            annual = spec.annual
        )
    },
    resolvedCountry = DEFAULT_PLAN_COUNTRY
)

/**
 * Resolves the market a phone number belongs to, longest dial code first so +971 beats +97 and
 * +1 never shadows a longer North American code. Returns null when nothing matches.
 */
fun countryFromPhone(phoneNumber: String, dialCodes: Map<String, String>): String? {
    val digits = phoneNumber.filter { it.isDigit() || it == '+' }
    if (!digits.startsWith("+")) return null

    return dialCodes.entries
        .filter { (_, dial) -> dial.length > 1 && digits.startsWith(dial.filter { c -> c.isDigit() || c == '+' }) }
        .maxByOrNull { (_, dial) -> dial.length }
        ?.key
}
