package com.rajamohan.mindmingle.presentation.theme

import androidx.compose.ui.graphics.Color

// ==========================================
// LIGHT THEME (Extracted from UI Design Image)
// ==========================================
// Primary Accent Warm Caramel / Sand Ochre (Active tabs, badges, chart bars)
val primaryLight = Color(0xFFD6A87C)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFF7EFE6)
val onPrimaryContainerLight = Color(0xFF593E23)

// Secondary Deep Charcoal Slate Navy (Header weather card, dark pills, keypad)
val secondaryLight = Color(0xFF343D4E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE4E7EE)
val onSecondaryContainerLight = Color(0xFF1D2433)

// Tertiary Muted Sage Green (Active device status dots, indicators)
val tertiaryLight = Color(0xFF3E6853)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFDCEDE3)
val onTertiaryContainerLight = Color(0xFF163728)

// Error Colors
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)

// Background & Surface (Soft Off-White/Grey Screen Background & White Cards from UI Image)
val backgroundLight = Color(0xFFEBECEE)
val onBackgroundLight = Color(0xFF22262E)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF22262E)
val surfaceVariantLight = Color(0xFFF2F3F5)
val onSurfaceVariantLight = Color(0xFF8C929E)

val outlineLight = Color(0xFFE0E3E8)
val outlineVariantLight = Color(0xFFECEEF2)
val scrimLight = Color(0xFF000000)

val inverseSurfaceLight = Color(0xFF2E333C)
val inverseOnSurfaceLight = Color(0xFFEBECEE)
val inversePrimaryLight = Color(0xFFE5BC95)

val surfaceDimLight = Color(0xFFE0E2E7)
val surfaceBrightLight = Color(0xFFFFFFFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8F9FA)
val surfaceContainerLight = Color(0xFFF2F3F5)
val surfaceContainerHighLight = Color(0xFFECEDF0)
val surfaceContainerHighestLight = Color(0xFFE5E7EB)

// Light Theme - Medium Contrast
val primaryLightMediumContrast = Color(0xFF8A5A2B)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFFE8B586)
val onPrimaryContainerLightMediumContrast = Color(0xFF000000)
val secondaryLightMediumContrast = Color(0xFF1D2433)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF4A556B)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF224B36)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF548069)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF2F3F5)
val onBackgroundLightMediumContrast = Color(0xFF22262E)
val surfaceLightMediumContrast = Color(0xFFFFFFFF)
val onSurfaceLightMediumContrast = Color(0xFF171A20)
val surfaceVariantLightMediumContrast = Color(0xFFE7EAEE)
val onSurfaceVariantLightMediumContrast = Color(0xFF555A64)
val outlineLightMediumContrast = Color(0xFF717782)
val outlineVariantLightMediumContrast = Color(0xFF8D939F)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2E333C)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF2F3F5)
val inversePrimaryLightMediumContrast = Color(0xFFE5BC95)
val surfaceDimLightMediumContrast = Color(0xFFD6D8DE)
val surfaceBrightLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF8F9FA)
val surfaceContainerLightMediumContrast = Color(0xFFECEDF0)
val surfaceContainerHighLightMediumContrast = Color(0xFFE0E2E7)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD5D7DD)

// Light Theme - High Contrast
val primaryLightHighContrast = Color(0xFF4A2F13)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF8A5A2B)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF0D121C)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF2B3444)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF0D281C)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF28513B)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF2F3F5)
val onBackgroundLightHighContrast = Color(0xFF22262E)
val surfaceLightHighContrast = Color(0xFFFFFFFF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE7EAEE)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF3F444E)
val outlineVariantLightHighContrast = Color(0xFF5D636E)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2E333C)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFE5BC95)
val surfaceDimLightHighContrast = Color(0xFFC8CACF)
val surfaceBrightLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF2F3F5)
val surfaceContainerLightHighContrast = Color(0xFFE0E2E7)
val surfaceContainerHighLightHighContrast = Color(0xFFD2D4D9)
val surfaceContainerHighestLightHighContrast = Color(0xFFC5C7CC)

// ==========================================
// DARK THEME — Premium deep teal glass (dev-dating flagship look)
// ==========================================
// Primary: near-white for high-contrast CTAs on deep teal glass surfaces
val primaryDark = Color(0xFFEFF5F5)
val onPrimaryDark = Color(0xFF0A1519)
val primaryContainerDark = Color(0xFF1B3238)
val onPrimaryContainerDark = Color(0xFFEFF5F5)

// Cyan-teal accent for badges, active states, links
val secondaryDark = Color(0xFF7DD8DC)
val onSecondaryDark = Color(0xFF06282B)
val secondaryContainerDark = Color(0xFF163A3E)
val onSecondaryContainerDark = Color(0xFFB9EEF1)

// Soft mint-green accent for success / verified states
val tertiaryDark = Color(0xFF8FD9A8)
val onTertiaryDark = Color(0xFF0C2A18)
val tertiaryContainerDark = Color(0xFF1C4530)
val onTertiaryContainerDark = Color(0xFFCFF3DC)

// Error Dark
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)

// Background & Surface (true black, matching the Welcome screen — no green/teal cast)
val backgroundDark = Color(0xFF0A0A0C)
val onBackgroundDark = Color(0xFFE9F1F2)
val surfaceDark = Color(0xFF141416)
val onSurfaceDark = Color(0xFFE9F1F2)
val surfaceVariantDark = Color(0xFF1E1E22)
val onSurfaceVariantDark = Color(0xFFA6ABB0)

val outlineDark = Color(0xFF3A3A3F)
val outlineVariantDark = Color(0xFF2A2A2E)
val scrimDark = Color(0xFF000000)

val inverseSurfaceDark = Color(0xFFE9F1F2)
val inverseOnSurfaceDark = Color(0xFF141416)
val inversePrimaryDark = Color(0xFF1B3238)

val surfaceDimDark = Color(0xFF0A0A0C)
val surfaceBrightDark = Color(0xFF2C2C30)
val surfaceContainerLowestDark = Color(0xFF060606)
val surfaceContainerLowDark = Color(0xFF101012)
val surfaceContainerDark = Color(0xFF141416)
val surfaceContainerHighDark = Color(0xFF1C1C20)
val surfaceContainerHighestDark = Color(0xFF26262A)

// Dark Theme - Medium Contrast
val primaryDarkMediumContrast = Color(0xFFF3CFAB)
val onPrimaryDarkMediumContrast = Color(0xFF2E1C09)
val primaryContainerDarkMediumContrast = Color(0xFFAC8056)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFBCC7E0)
val onSecondaryDarkMediumContrast = Color(0xFF0F1724)
val secondaryContainerDarkMediumContrast = Color(0xFF6F7B94)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFA1DBC0)
val onTertiaryDarkMediumContrast = Color(0xFF042618)
val tertiaryContainerDarkMediumContrast = Color(0xFF589075)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF14171D)
val onBackgroundDarkMediumContrast = Color(0xFFE6E8EC)
val surfaceDarkMediumContrast = Color(0xFF1F232C)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF2B303C)
val onSurfaceVariantDarkMediumContrast = Color(0xFFC0C7D7)
val outlineDarkMediumContrast = Color(0xFF969DAE)
val outlineVariantDarkMediumContrast = Color(0xFF767D8E)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE6E8EC)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF1F232C)
val inversePrimaryDarkMediumContrast = Color(0xFFB5895E)
val surfaceDimDarkMediumContrast = Color(0xFF14171D)
val surfaceBrightDarkMediumContrast = Color(0xFF454C5C)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0A0C10)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1B1E26)
val surfaceContainerDarkMediumContrast = Color(0xFF252A35)
val surfaceContainerHighDarkMediumContrast = Color(0xFF303644)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3B4152)

// Dark Theme - High Contrast
val primaryDarkHighContrast = Color(0xFFFFF0E2)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFE5BC95)
val onPrimaryContainerDarkHighContrast = Color(0xFF1D0E00)
val secondaryDarkHighContrast = Color(0xFFF2F5FF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFF9EAAC2)
val onSecondaryContainerDarkHighContrast = Color(0xFF060E1A)
val tertiaryDarkHighContrast = Color(0xFFEFFFF7)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF88C1A4)
val onTertiaryContainerDarkHighContrast = Color(0xFF001A0F)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF14171D)
val onBackgroundDarkHighContrast = Color(0xFFE6E8EC)
val surfaceDarkHighContrast = Color(0xFF1F232C)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF2B303C)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFE4E8F5)
val outlineVariantDarkHighContrast = Color(0xFFB8BFD0)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE6E8EC)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF6E4823)
val surfaceDimDarkHighContrast = Color(0xFF14171D)
val surfaceBrightDarkHighContrast = Color(0xFF505769)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1D212A)
val surfaceContainerDarkHighContrast = Color(0xFF2B303C)
val surfaceContainerHighDarkHighContrast = Color(0xFF363C4B)
val surfaceContainerHighestDarkHighContrast = Color(0xFF42495B)
// ==========================================
// MINDMINGLE BRAND LOGO GRADIENTS & TOKENS
// ==========================================
object MindMingleBrand {
    val CaramelAccent = primaryLight      // #D6A87C (Warm Caramel / Sand Ochre)
    val VioletAccent = Color(0xFFA855F7)  // #A855F7 (Vibrant Violet / Purple)
    val CanvasObsidian = backgroundDark  // #0A0A0C
    val SurfaceDark = surfaceDark        // #141416
}

// ==========================================
// ANONYMOUS CHAT ACCENTS
// ==========================================
val anonymousAccentOneLight = Color(0xFF7C4DFF)
val anonymousAccentOneVariantLight = Color(0xFFB388FF)
val anonymousAccentTwoLight = Color(0xFF00A896)
val anonymousAccentTwoVariantLight = Color(0xFF6FE0CF)
val anonymousAccentThreeLight = Color(0xFFE9556F)
val anonymousAccentThreeVariantLight = Color(0xFFFFA69E)
val anonymousAccentFourLight = Color(0xFF2979FF)
val anonymousAccentFourVariantLight = Color(0xFF82B1FF)
val anonymousAccentFiveLight = Color(0xFFEF8C1F)
val anonymousAccentFiveVariantLight = Color(0xFFFFC96B)
val anonymousBackdropTopLight = Color(0xFFF8F9FA)
val anonymousBackdropBottomLight = Color(0xFFEBECEE)
val anonymousWhisperLight = Color(0xFFF3ECFF)
val onAnonymousWhisperLight = Color(0xFF3B2A63)

val anonymousAccentOneDark = Color(0xFF9B7DFF)
val anonymousAccentOneVariantDark = Color(0xFF5B39C4)
val anonymousAccentTwoDark = Color(0xFF7DD8DC)
val anonymousAccentTwoVariantDark = Color(0xFF2C7F86)
val anonymousAccentThreeDark = Color(0xFFFF8FA3)
val anonymousAccentThreeVariantDark = Color(0xFFB44E63)
val anonymousAccentFourDark = Color(0xFF7FB2FF)
val anonymousAccentFourVariantDark = Color(0xFF3C63C4)
val anonymousAccentFiveDark = Color(0xFFFFC46B)
val anonymousAccentFiveVariantDark = Color(0xFFB57A26)
val anonymousBackdropTopDark = Color(0xFF101012)
val anonymousBackdropBottomDark = Color(0xFF0A0A0C)
val anonymousWhisperDark = Color(0xFF1B1830)
val onAnonymousWhisperDark = Color(0xFFD9CEFF)
val onAnonymousAccentLight = Color(0xFFFFFFFF)
val onAnonymousAccentDark = Color(0xFF0A1519)
